104corp/college.104.com.tw

.env.development
.env.production
.env.staging
package-lock.json
package.json
src/main.js
src/stores/Error.js
src/utils/errorHandler.js
src/utils/typeChecker.js
test/utils/stores/Error.test.js
test/utils/typeChecker.test.js
vite.config.js

CSROP-3969

---

src/utils/urlHandler.js
test/utils/urlHandler.test.js

這 PR 主要類型是什麼？
**需求單號：** [CSROP-3988](https://jira.104.com.tw/browse/CSROP-3988)
---

CSROP-3988 [ 共用功能 ] urlHandler

---

package-lock.json
package.json
src/stores/Event.js
src/stores/Instagram.js
src/stores/Podcast.js
test/utils/stores/Event.test.js
test/utils/stores/Instagram.test.js
test/utils/stores/Podcast.test.js

這 PR 主要類型是什麼？
**需求單號：** [CSROP-3980](https://jira.104.com.tw/browse/CSROP-3980)
---

CSROP-3980 - [ 資料 ] store

---

src/common/domainConfig.js
src/views/Index/components/NavBar.vue
src/views/Index/components/SideBar.vue
src/views/Index/index.vue

這 PR 主要類型是什麼？
**需求單號：** [CSROP-3978](https://104corp.atlassian.net/browse/CSROP-3978)
---

CSROP-3978 [元件] NavBar、SideBar

---

src/stores/Job.js

這 PR 主要類型是什麼？
**需求單號：** [CSROP-4011](https://104corp.atlassian.net/browse/CSROP-4011/)
---

CSROP-4011 [資料] store Job

---

components.d.ts
src/components/BaseImage.vue
src/main.js

這 PR 主要類型是什麼？
**需求單號：** [CSROP-3987](https://104corp.atlassian.net/browse/CSROP-3987)
---

CSROP-3987 [ 元件 ] BaseImage模組

---

components.d.ts
src/stores/QA.js
src/views/Index/components/SectionGetHelp.vue
src/views/Index/index.vue

這 PR 主要類型是什麼？
**需求單號：** [CSROP-3966](https://104corp.atlassian.net/browse/CSROP-3966)
---

CSROP-3966 [ 元件 ] section - getHelp

---

components.d.ts
src/assets/styles/base.scss
src/stores/Tool.js
src/views/Index/components/SectionTool.vue
src/views/Index/components/ToolShowcase.vue
src/views/Index/index.vue

這 PR 主要類型是什麼？
**需求單號：** [CSROP-4008](https://104corp.atlassian.net/browse/CSROP-4008)
---

CSROP-4008 [ 元件 ] section - tool

---

src/stores/ProfilePortfolio.js
src/views/Index/components/SectionStories.vue
src/views/Index/index.vue

這 PR 主要類型是什麼？
**需求單號：** [CSROP-3965](https://104corp.atlassian.net/browse/CSROP-3965)
---

CSROP-3965 [ 元件 ] section - stories

---

.vscode/blueprint-templates/api-module/__pascalCase_name__.js
.vscode/blueprint-templates/test-store/__pascalCase_name__.test.js
.vscode/template.code-snippets
src/apis/home/ResumeSample.js
src/apis/index.js
src/stores/ProfileResume.js
test/apis/home/resumeSample.test.js
test/stores/ProfileResume.test.js

這 PR 主要類型是什麼？
**需求單號：** CSROP-4048
---

CSROP-4048- [ api ] store ProfileResume & 開發模板

---

src/main.js

這 PR 主要類型是什麼？
**需求單號：** CSROP-4005
---

CSROP-4005-封站錯誤處理

---

src/apis/home/giverQaList.js
src/apis/index.js
src/stores/QA.js
src/views/Index/components/SectionGetHelp.vue
test/apis/home/giverQaList.test.js
test/stores/QA.test.js

這 PR 主要類型是什麼？
**需求單號：** [CSROP-4047](https://104corp.atlassian.net/browse/CSROP-4047)
---

CSROP-4047 [ api ] QA

---

src/apis/home/eventList.js
src/apis/index.js
src/stores/Event.js
src/views/Index/components/CardEvent.vue
src/views/Index/components/SectionCover.vue
test/apis/home/eventList.test.js
test/stores/Event.test.js

這 PR 主要類型是什麼？
**需求單號：** CSROP-3984
---

CSROP-3984-[ api ] store Event

---

src/apis/college/news.js
src/apis/index.js
src/stores/Announcement.js
src/views/Index/components/ScrollingAnnouncement.vue
src/views/Index/components/SectionCover.vue
test/apis/college/news.test.js
test/stores/Announcement.test.js

這 PR 主要類型是什麼？
**需求單號：** [CSROP-4055](https://104corp.atlassian.net/browse/CSROP-4055)
---

CSROP-4055 [ api ] Announcemenet

---

src/apis/home/blogs.js
src/apis/index.js
src/stores/ArticleNews.js
src/views/Index/components/SectionArticle.vue
test/apis/home/blogs.test.js
test/stores/ArticleNews.test.js

這 PR 主要類型是什麼？
**需求單號：** CSROP-4045
---

CSROP-4045-[api] store ArticleNews

---

src/apis/home/careerOpportunities.js
src/apis/home/internJobList.js
src/apis/home/keywords.js
src/apis/home/partTimeJobList.js
src/apis/index.js
src/stores/Job.js
src/views/Index/components/SectionCover.vue
test/apis/home/careerOpportunities.test.js
test/apis/home/internJobList.test.js
test/apis/home/keywords.test.js
test/apis/home/partTimeJobList.test.js
test/stores/Job.test.js

這 PR 主要類型是什麼？
**需求單號：** CSROP-3985
---

CSROP-3985

---

src/views/Index/components/SectionResume.vue

這 PR 主要類型是什麼？
**需求單號：** CSROP-4064
---

CSROP-4064

---

src/views/Index/components/ScrollingAnnouncement.vue
src/views/Index/components/SectionCover.vue
src/views/Index/components/SectionStories.vue
src/views/Index/components/ToolShowcase.vue
uno.config.js

這 PR 主要類型是什麼？
**需求單號：** CSROP-4063
---

CSROP-4063-stories swipe操作

---

script/generateKey.sh
src/main.js

這 PR 主要類型是什麼？
**需求單號：** CSROP-4067
---

CSROP-4067-sentry dsn調整 & generateKey.sh修正

---

src/stores/Announcement.js
src/stores/ArticleNews.js
src/stores/Event.js
src/stores/Instagram.js
src/stores/Job.js
src/stores/Podcast.js
src/stores/ProfilePortfolio.js
src/stores/ProfileResume.js
src/stores/QA.js
src/stores/User.js
src/views/Index/components/SectionArticle.vue
src/views/Index/components/SectionFollowUs.vue
src/views/Index/components/SectionResume.vue

這 PR 主要類型是什麼？
**需求單號：** CSROP-4066
---

CSROP-4066

---

src/stores/Instagram.js
src/stores/Podcast.js
test/stores/Instagram.test.js
test/stores/Podcast.test.js

這 PR 主要類型是什麼？
**需求單號：** CSROP-4057
---

CSROP-4057

---

package.json

CSROP-3766-指令修正

---

package.json
script/buildspec_preview.yml
src/views/Index/components/CardEvent.vue

CSROP-3766

---

src/components/GlobalHeader.vue
src/stores/Tool.js
src/views/Index/components/SectionStories.vue

CSROP-4080

---

src/views/Index/components/SectionCover.vue

CSROP-4107

---

src/apis/home/internJobList.js
src/apis/home/partTimeJobList.js
src/stores/Job.js
src/views/Index/components/SectionCover.vue
test/apis/home/internJobList.test.js
test/apis/home/partTimeJobList.test.js
test/stores/Job.test.js

CSROP-4131

---

package.json
src/apis/home/internJobList.js
src/apis/home/partTimeJobList.js
src/stores/Job.js
src/views/Index/components/SectionCover.vue
test/apis/home/internJobList.test.js
test/apis/home/partTimeJobList.test.js
test/stores/Job.test.js

ITPMSOEDREQ-2329

---

src/views/Index/components/SectionCover.vue

CSROP-4159 - [功能] 調整gtm

---

src/views/Index/components/SectionCover.vue

CSROP-4164 - [功能] 更多按鈕gtm設定

---

buildspec.yml
package.json
src/views/Index/components/SectionCover.vue

ITPMSOEDREQ-2397

---

src/components/GlobalHeader.vue

[CSROP-4191] 人力銀行連結調整

---

.github/104z-workflows/buildspec_develop.yml
.github/104z-workflows/buildspec_production.yml
.github/104z-workflows/buildspec_staging.yml

CSROP-4190
